version: "3"
services:
  api:
    container_name: putting-back
    image: scottharben/person-back:latest
    networks:
      - local_net
    depends_on:
      - db
    ports:
      - "8080:8080"
    environment:
      MYSQL_HOST: db
      MYSQL_PORT: 3306
      MYSQL_DATABASE: Person
      MYSQL_USER: superuser
      MYSQL_PASSWORD: superuser
    restart: always
  db:
    container_name: mysql
    image: mysql
    networks:
      - local_net
    volumes:
      - db-data:/var/lib/mysql
    ports:
      - "3306:3306"
    command: --default-authentication-plugin=mysql_native_password
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: Person
      MYSQL_USER: superuser
      MYSQL_PASSWORD: superuser
volumes:
  db-data:
networks:
  local_net:
    driver: bridge
